### PR TITLE
Use horizontal form on user settings page

### LINKED ISSUE #166: Don't use table tag on user settings page

### PR DESCRIPTION
**Pull request by OmTheTurtle**
Closes #166

### CODE REVIEW

**Comment by OmTheTurtle** [comment]
> Can you add some spacing to the right of those fields that have no visibility toggle?

Is it possible to do this from UIkit 2 on only large screens? Because if I just add margin it looks weird on mobile.

**Comment by falusi94** [comment]
Yes it is, here you can find the docs for it
https://getuikit.com/v2/docs/utility.html#visibility-utilities

**Comment by OmTheTurtle** [comment]
I decided to use media query instead, spacer div just doesn't seem the right way to do it.

**Comment by OmTheTurtle** [comment]
I don't really follow how the icons would solve the issue with the margin / checkbox.

**Comment by falusi94** [comment]
My idea is to change the checkboxes to icons (lock opened/closed). In this case they can be moved inside the right side of the form input and the plus 'column' could be removed.

**Pull request closed without merging**
