### PR TITLE
Permit the user's date of birth on svie application

### PR DESCRIPTION
**Pull request by emanreyalp**

### CODE REVIEW

**Comment by emanreyalp** [comment]
[Ha nincs szül. hely vagy idő vagy anyja neve, akkor a SVIE-be jelentkezős form össze csúszik és hiányos lesz](https://trello.com/c/hDkw09wA/297-ha-nincs-sz%C3%BCl-hely-vagy-id%C5%91-vagy-anyja-neve-akkor-a-svie-be-jelentkez%C5%91s-form-%C3%B6ssze-cs%C3%BAszik-%C3%A9s-hi%C3%A1nyos-lesz)

**Comment by salierri** [comment]
The requires only happen on client side, so it doesn't fully solve the linked problem. If that's not supposed to be in the scope of this PR, then this is an approve.

**Comment by falusi94** [comment]
I can just add, that I've checked, the form accepts anything for date of birth, but if rails can't parse it, it will be an empty string in the end. So a mispell is enough to fail the validation, it doesn't need any kind of client side hack.

**Comment by emanreyalp** [comment]
@falusi94 Do you mean on the edit profile page?

**Comment by falusi94** [comment]
Maybe there too, but I have tested on the svie application page. Meanwhile I've figured out, that you used `date_field_tag` as input, but it is not supported by Safari, so I could easily write anything into that field.

**Pull request merged**
