### PR TITLE
Fix wkhtmltopdf

### PR DESCRIPTION
**Pull request by falusi94**
Here I started fixing the pdf generation, added more method, but none of the is working.

- the `wkhtmltopdf` from alpine is not qt patched and generates empty pdf
- the `wkhtmltopdf-binary-edge` does not solve the problem
- updating the current `wkhtmltopdf-binary` neither
- the binary from [here](https://github.com/madnight/docker-alpine-wkhtmltopdf) generates black squares instead of the characters

### CODE REVIEW

**Comment by OmTheTurtle** [comment]
Any update on this?

**Comment by falusi94** [comment]
Not really, I didn't have time to touch this part 😢

**Comment by OmTheTurtle** [comment]
@falusi94 @kiralybalint Can somebody take a look at this issue?

**Comment by SepsiLaszlo** [comment]
I couldn't get `wkhtmltopdf ` to work. I found two alternatives. The first is [Gotenberg](https://github.com/thecodingmachine/gotenberg), this is a HTML to PDF converter application that runs in docker. I think this would be an easy solution, but the container's size is +800MB so it is a very heavy dependency. Tha anoter solution is [Prawn](https://github.com/prawnpdf/prawn). It is a pure Ruby PDF genereator, but can't convert HTML to PDF. We must use its DSL to describe a PDF. This could make creating complex PDFs hard, but the files we have now are doable. I think the first option would be good enough, until we can fix `wkhtml`.

**Comment by falusi94** [comment]
Well, about the Gotenberg, probably it has to be downloaded very seldom so I think the size of the dependency does not matter, but I'd go with some easier solution. Continuing on the idea of easiness, I'd add the printer friendly view of the page as an option. True that in one hand there's no pdf generated, but I think it should not be a problem and also an external dependency could be eliminated. The same solution is used on the delegates page if I remember right. I suspect that with some insignificant modification the current solution could be reused.

**Comment by SepsiLaszlo** [comment]
I made the suggested changes in this pr: #265

**Pull request closed without merging**
